name: Compile Fortran Examples

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install gfortran
      run: sudo apt-get install -y gfortran

    - name: Compile mylib.f
      run: gfortran -shared -o mylib.dll -fPIC mylib.f

    - name: Compile main.f
      run: gfortran -o main.exe main.f mylib.dll

    - name: Copy DLL
      run: |
        if [ ! -f ./mylib.dll ]; then
          cp mylib.dll ./
        fi

    - name: Run the executable
      run: LD_LIBRARY_PATH=. ./main.exe
